### ISSUE TITLE
Removal of console.log on client

### ISSUE THREAD

**Issue by johannel00** [quavedev/analytics#1]
Hey @filipenevola. I've started using this package and I love its simplicity. Can I suggest that you please remove this line in the next version. It's clogs the console on the client. Thanks for all the great progress with your contributions to Meteor.

https://github.com/quavedev/analytics/blob/81ced56327b52a1d1046c28a68ddec48db2db943/analytics-client.js#L81

**Comment by filipenevola** [comment]
hi @johannel00 fixed in 1.0.1

Thank you for the report.

**Comment by johannel00** [comment]
> hi @johannel00 fixed in 1.0.1
> 
> Thank you for the report.

Thanks @filipenevola !
